M48
; DRILL file {KiCad (6.0.5)} date Wed Feb 15 13:54:11 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-15T13:54:11-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0433
%
G90
G05
T1
X2.75Y-3.9
X2.85Y-3.9
X3.05Y-3.9
X3.15Y-3.9
X3.35Y-3.9
X3.45Y-3.9
X3.65Y-3.9
X3.75Y-3.9
X3.95Y-3.9
X4.05Y-3.9
X4.25Y-3.9
X4.35Y-3.9
T0
M30
