M48
; DRILL file {KiCad (6.0.5)} date Wed Feb 15 13:54:11 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-15T13:54:11-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0433
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X2.75Y-4.0
X2.85Y-4.0
X3.05Y-4.0
X3.15Y-4.0
X3.35Y-4.0
X3.45Y-4.0
X3.65Y-4.0
X3.75Y-4.0
X3.95Y-4.0
X4.05Y-4.0
X4.25Y-4.0
X4.35Y-4.0
T2
X2.5Y-3.9
X4.6Y-3.9
T0
M30
