M48
; DRILL file {KiCad (6.0.5)} date Sat Jan 21 13:29:45 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-21T13:29:45-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X9.25Y-2.25
X9.25Y-3.5
X9.25Y-4.5
X9.25Y-5.75
T0
M30
